[package]
name = "wgps"
version = "0.1.0"
edition = "2021"

[dependencies]
willow-data-model = { path = "../data-model", version = "0.1.0" }
ufotofu = { version = "0.4.2", features = ["std"] }

[lints]
workspace = true
