[package]
name = "meadowcap"
version = "0.1.0"
edition = "2021"

[dependencies]
signature = "2.2.0"
ufotofu = "0.3.0"

[dependencies.willow-data-model]
path = "../data-model"
features = ["dev"]

[lints]
workspace = true
