[package]
name = "meadowcap"
version = "0.1.0"
edition = "2021"

[features]
default = []
dev = ["dep:arbitrary"]

[dependencies]
signature = "2.2.0"
ufotofu = { version = "0.4.2", features = ["std"] }
arbitrary = { version = "1.0.2", features = ["derive"], optional = true }
either = "1.13.0"
syncify = "0.1.0"

[dependencies.willow-data-model]
path = "../data-model"
features = ["dev"]

[lints]
workspace = true
